/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 museu1.glb
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import './App.css'

export function ModelMuseu({
  sendCambio2,
  sendCambio3,
  sendArmor,
  sendGuitar1,
  sendYunke,
  sendTambores,
  props,
  playState,
  tiempo,
  camZ,
  cam1,
  cam2,
  cam3,
  cam4,
  cam5,
  cam6,
}) {

  console.log('tiempo: ' + tiempo)

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/museu1.glb");
  const { actions } = useAnimations(animations, group);


  useEffect(() => {
    console.log(actions);
    if (cam1) {
      if (playState) {
        actions["CameraAction.001"].timeScale = 0.3;
        actions["CameraAction.001"].play();
      } else {
        actions["CameraAction.001"].timeScale = 0;
      }
    } else if (cam2) {
      actions["Camera.001Action"].play();
      actions["Camera.001Action"].timeScale = 0;
      actions["Camera.001Action"].time = tiempo;
      console.log(actions["Camera.001Action"].time)
      if (tiempo >= 3.15) {
        sendCambio2(false)
      }

    } else if (cam3) {
      actions["Camera.002Action"].play();
      actions["Camera.002Action"].timeScale = 0;
      actions["Camera.002Action"].time = tiempo;
      if (tiempo >= 3.1) {
        sendCambio3(false)
      }

    } else if (cam4) {
      actions["Camera.003Action"].play();
      actions["Camera.003Action"].timeScale = 0;
      actions["Camera.003Action"].time = tiempo;

    } else if (cam5) {
      actions["Camera.004Action"].play();
      actions["Camera.004Action"].timeScale = 0;
      actions["Camera.004Action"].time = tiempo;

    } else if (cam6) {
      actions["Camera.005Action"].play();
      actions["Camera.005Action"].timeScale = 0;
      actions["Camera.005Action"].time = tiempo;

    }
  }, [playState, tiempo, cam1, cam2, cam3, cam4, cam5, cam6]);



  const LanzarYunke = () => {
    sendYunke(0)
    console.log('Yunke clicked!')
  }

  const LanzarArmor = () => {
    sendArmor(1)
  }

  const LanzarGuitar1 = () => {
    sendGuitar1(2)
  }

  const LanzarTambores = () => {
    sendTambores(3)
  }

  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  }, [hovered])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Size"
          position={[19.43, 5.22, -17.9]}
          rotation={[-2.68, 0, 0]}
          scale={0.01}
        />
        <group
          name="Size001"
          position={[19.61, 5.25, -17.9]}
          rotation={[-2.87, 0.38, 0.92]}
          scale={0.01}
        />
        <group
          name="MESH_BS09_NeriumOleander_A_LOD1"
          position={[5.03, 1.01, 3.46]}
          scale={0.01}
        >
          <mesh
            name="MI_LOD1"
            geometry={nodes.MI_LOD1.geometry}
            material={materials["guitar_base_in.001"]}
          />
          <mesh
            name="MI_LOD1_001"
            geometry={nodes.MI_LOD1_001.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD1_002"
            geometry={nodes.MI_LOD1_002.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_A_LOD2"
          position={[-6.05, 1.01, -3.73]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD2"
            geometry={nodes.MI_LOD2.geometry}
            material={materials["guitar_base.009"]}
          />
          <mesh
            name="MI_LOD2_001"
            geometry={nodes.MI_LOD2_001.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD2_002"
            geometry={nodes.MI_LOD2_002.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_M_LOD0"
          position={[0.21, 1.01, 2.52]}
          scale={0.02}
        />
        <group
          name="MESH_BS09_NeriumOleander_M_LOD1"
          position={[8.09, 1.01, 0.05]}
          scale={0.02}
        />
        <group
          name="MESH_BS09_NeriumOleander_M_LOD2"
          position={[1.75, 1.01, -3.73]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD2001"
            geometry={nodes.MI_LOD2001.geometry}
            material={materials["guitar_base.016"]}
          />
          <mesh
            name="MI_LOD2_001001"
            geometry={nodes.MI_LOD2_001001.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD2_002001"
            geometry={nodes.MI_LOD2_002001.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_Y_LOD0"
          position={[-1.52, 1.01, -4.77]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD0002"
            geometry={nodes.MI_LOD0002.geometry}
            material={materials["guitar_base.016"]}
          />
          <mesh
            name="MI_LOD0_001002"
            geometry={nodes.MI_LOD0_001002.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD0_002002"
            geometry={nodes.MI_LOD0_002002.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_Y_LOD2"
          position={[9.56, 1.01, -3.73]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD2002"
            geometry={nodes.MI_LOD2002.geometry}
            material={materials.BS09_Bark01_su}
          />
          <mesh
            name="MI_LOD2_001002"
            geometry={nodes.MI_LOD2_001002.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD2_002002"
            geometry={nodes.MI_LOD2_002002.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_M_LOD0001"
          position={[13.48, 1.01, -3.53]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD0003"
            geometry={nodes.MI_LOD0003.geometry}
            material={materials["guitar_base.016"]}
          />
          <mesh
            name="MI_LOD0_001003"
            geometry={nodes.MI_LOD0_001003.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD0_002003"
            geometry={nodes.MI_LOD0_002003.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_A_LOD0001"
          position={[24.93, 0, 0]}
          scale={0.01}
        />
        <group
          name="MESH_BS09_NeriumOleander_A_LOD2001"
          position={[-2.02, 1.01, -1.24]}
          scale={0.02}
        />
        <group
          name="MESH_BS09_NeriumOleander_Y_LOD2001"
          position={[3.34, 1.01, -0.35]}
          scale={0.02}
        />
        <group
          name="MESH_BS09_NeriumOleander_Y_LOD0001"
          position={[-3.24, 1.01, 3.82]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD0005"
            geometry={nodes.MI_LOD0005.geometry}
            material={materials["guitar_base.017"]}
          />
          <mesh
            name="MI_LOD0_001005"
            geometry={nodes.MI_LOD0_001005.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD0_002005"
            geometry={nodes.MI_LOD0_002005.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group
          name="MESH_BS09_NeriumOleander_M_LOD0002"
          position={[5.9, 1.01, -3.64]}
          scale={0.02}
        >
          <mesh
            name="MI_LOD0006"
            geometry={nodes.MI_LOD0006.geometry}
            material={materials["guitar_base.018"]}
          />
          <mesh
            name="MI_LOD0_001006"
            geometry={nodes.MI_LOD0_001006.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            name="MI_LOD0_002006"
            geometry={nodes.MI_LOD0_002006.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Плоскость"
          position={[4.75, 3.18, 18.86]}
          rotation={[0, -0.19, 0]}
          scale={0.89}
        />
        <group name="Med_kit" position={[-20.45, 6.2, -17.89]} scale={3.67}>
          <primitive object={nodes["2"]} />
          <primitive object={nodes["1"]} />
          <group name="Med_Kit">
            <skinnedMesh
              name="Плоскость004"
              geometry={nodes.Плоскость004.geometry}
              material={materials["Material.011"]}
              skeleton={nodes.Плоскость004.skeleton}
            />
            <skinnedMesh
              name="Плоскость004_1"
              geometry={nodes.Плоскость004_1.geometry}
              material={materials["Material.035"]}
              skeleton={nodes.Плоскость004_1.skeleton}
            />
          </group>
        </group>
        <group
          name="GUITAR"
          position={[2.95, 8.17, 21.92]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={6.37}
        >
          <mesh
            name="BODY_Main"
            geometry={nodes.BODY_Main.geometry}
            material={materials["Main Body Black.002"]}
            position={[0.11, 0, 0]}
            scale={0.3}
          >
            <mesh
              name="Bolt001"
              geometry={nodes.Bolt001.geometry}
              material={materials["Gold.002"]}
              position={[-1.55, -0.06, 0.02]}
              rotation={[0.7, -0.07, 0.06]}
            />
            <mesh
              name="Bolt002"
              geometry={nodes.Bolt002.geometry}
              material={materials["Gold.002"]}
              position={[-1.55, 0.04, 0.02]}
              rotation={[0.7, -0.07, 0.06]}
            />
            <mesh
              name="Bolt003"
              geometry={nodes.Bolt003.geometry}
              material={materials["Gold.002"]}
              position={[-1.55, 0.13, 0.02]}
              rotation={[0.7, -0.07, 0.06]}
            />
            <mesh
              name="Bp1"
              geometry={nodes.Bp1.geometry}
              material={materials["Wood 1.004"]}
            />
            <mesh
              name="Bp2"
              geometry={nodes.Bp2.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={nodes.Cube.material}
              position={[-1.36, -0.37, 0]}
              scale={[0.06, 0, 0.06]}
            />
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials["Gold.002"]}
              position={[-0.82, 0.03, -0.05]}
              scale={[0.04, 0.15, 0.07]}
            />
            <mesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials["Metal.010"]}
              position={[1.2, 0.03, 0.02]}
              scale={[0, 0.09, 0.01]}
            />
            <mesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials["Plastic.002"]}
              position={[1.2, 0.03, 0.02]}
              scale={[0, 0.09, 0.01]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={nodes.Cylinder.material}
              position={[-1.59, -0.08, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            />
            <mesh
              name="Cylinder001"
              geometry={nodes.Cylinder001.geometry}
              material={materials["Gold.002"]}
              position={[-1.8, -0.37, 0.04]}
            >
              <mesh
                name="Plane018"
                geometry={nodes.Plane018.geometry}
                material={materials["Gold.002"]}
                position={[0, 0.04, -0.01]}
                scale={0.01}
              />
            </mesh>
            <mesh
              name="Cylinder002"
              geometry={nodes.Cylinder002.geometry}
              material={materials["Gold.002"]}
              position={[-1.52, -0.37, 0.04]}
              rotation={[0, 0, 2.59]}
            >
              <mesh
                name="Plane019"
                geometry={nodes.Plane019.geometry}
                material={materials["Gold.002"]}
                position={[0, 0.04, -0.01]}
                scale={0.01}
              />
            </mesh>
            <mesh
              name="Cylinder003"
              geometry={nodes.Cylinder003.geometry}
              material={materials["Gold.002"]}
              position={[-1.61, 0.15, -0.05]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.02}
            >
              <mesh
                name="Cylinder004"
                geometry={nodes.Cylinder004.geometry}
                material={nodes.Cylinder004.material}
                position={[0, 0.15, 0]}
                scale={[0.85, 1, 0.85]}
              />
            </mesh>
            <group
              name="Cylinder005"
              position={[-1.61, 0.15, -0.1]}
              rotation={[0, 0, 0.59]}
              scale={0.01}
            >
              <mesh
                name="Cylinder022"
                geometry={nodes.Cylinder022.geometry}
                material={materials["Material.039"]}
              />
              <mesh
                name="Cylinder022_1"
                geometry={nodes.Cylinder022_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <group
              name="Cylinder006"
              position={[-1.61, 0.11, -0.1]}
              rotation={[0, 0, -0.67]}
              scale={0.01}
            >
              <mesh
                name="Cylinder023"
                geometry={nodes.Cylinder023.geometry}
                material={materials["Material.040"]}
              />
              <mesh
                name="Cylinder023_1"
                geometry={nodes.Cylinder023_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <group
              name="Cylinder007"
              position={[-1.61, -0.04, -0.1]}
              rotation={[0, 0, 0.59]}
              scale={0.01}
            >
              <mesh
                name="Cylinder024"
                geometry={nodes.Cylinder024.geometry}
                material={materials["Material.041"]}
              />
              <mesh
                name="Cylinder024_1"
                geometry={nodes.Cylinder024_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <group
              name="Cylinder008"
              position={[-1.61, -0.08, -0.1]}
              rotation={[0, 0, -0.67]}
              scale={0.01}
            >
              <mesh
                name="Cylinder025"
                geometry={nodes.Cylinder025.geometry}
                material={materials["Material.042"]}
              />
              <mesh
                name="Cylinder025_1"
                geometry={nodes.Cylinder025_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <group
              name="Cylinder009"
              position={[-1.61, 0.06, -0.1]}
              rotation={[0, 0, 0.01]}
              scale={0.01}
            >
              <mesh
                name="Cylinder026"
                geometry={nodes.Cylinder026.geometry}
                material={materials["Material.043"]}
              />
              <mesh
                name="Cylinder026_1"
                geometry={nodes.Cylinder026_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <group
              name="Cylinder010"
              position={[-1.61, 0.01, -0.1]}
              rotation={[0, 0, 0.78]}
              scale={0.01}
            >
              <mesh
                name="Cylinder027"
                geometry={nodes.Cylinder027.geometry}
                material={materials["Material.044"]}
              />
              <mesh
                name="Cylinder027_1"
                geometry={nodes.Cylinder027_1.geometry}
                material={materials["Metal.010"]}
              />
            </group>
            <mesh
              name="NurbsPath"
              geometry={nodes.NurbsPath.geometry}
              material={materials["Metal.011"]}
              position={[-1.36, -0.37, -0.05]}
            />
            {/* <mesh name="NurbsPath001" material={materials['Metal.012']} position={[-1.36, -0.41, -0.05]} /> */}
            <mesh
              name="NurbsPath002"
              geometry={nodes.NurbsPath002.geometry}
              material={materials["Metal.013"]}
              position={[-1.37, -0.46, -0.05]}
            />
            <mesh
              name="NurbsPath003"
              geometry={nodes.NurbsPath003.geometry}
              material={materials["Metal.014"]}
              position={[-1.36, -0.5, -0.05]}
            />
            <mesh
              name="NurbsPath004"
              geometry={nodes.NurbsPath004.geometry}
              material={materials["Metal.010"]}
              position={[-1.36, -0.54, -0.05]}
            />
            <mesh
              name="NurbsPath005"
              geometry={nodes.NurbsPath005.geometry}
              material={materials["Metal.010"]}
              position={[-1.37, -0.59, -0.05]}
            />
            <mesh
              name="Pickup_bridge_1"
              geometry={nodes.Pickup_bridge_1.geometry}
              material={materials["Pickup Bridge.002"]}
              position={[-1.34, 0.03, -0.02]}
              rotation={[0, 0, -0.3]}
              scale={[0.55, 0.89, 0.22]}
            />
            <mesh
              name="Pickup_bridge_2"
              geometry={nodes.Pickup_bridge_2.geometry}
              material={materials["Metal.010"]}
              position={[-1.3, 0.15, 0.02]}
              rotation={[1.57, 0, 0]}
              scale={0.01}
            />
            <mesh
              name="Plane016"
              geometry={nodes.Plane016.geometry}
              material={materials["Metal.010"]}
              position={[-1.36, -0.37, -0.05]}
            />
            <mesh
              name="Plane017"
              geometry={nodes.Plane017.geometry}
              material={materials["Main Body Black.002"]}
              position={[0, 0, 0.02]}
              rotation={[0, -0.01, 0]}
            />
            <mesh
              name="Plane020"
              geometry={nodes.Plane020.geometry}
              material={materials["Gold.002"]}
              position={[-1.42, 0.03, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.19, 0.28, 0.17]}
            />
            <group
              name="Plane021"
              position={[0.34, 0.03, 0.02]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1.06, 0.17, 0.12]}
            >
              <mesh
                name="Plane051"
                geometry={nodes.Plane051.geometry}
                material={materials["Wood 1.005"]}
              />
              <mesh
                name="Plane051_1"
                geometry={nodes.Plane051_1.geometry}
                material={materials["Wood 3.002"]}
              />
              <mesh
                name="Plane051_2"
                geometry={nodes.Plane051_2.geometry}
                material={materials["Plastic.002"]}
              />
              <mesh
                name="Plane030"
                geometry={nodes.Plane030.geometry}
                material={materials["Material.045"]}
                position={[0.88, 0.03, -0.01]}
                scale={[0.04, 0.29, 0.42]}
              />
            </group>
            <mesh
              name="Plane022"
              geometry={nodes.Plane022.geometry}
              material={materials["Gold.002"]}
              position={[-1.51, -0.06, 0.03]}
              rotation={[-Math.PI, 0, 0]}
              scale={[-0.02, -0.02, -0.01]}
            />
            <mesh
              name="Plane023"
              geometry={nodes.Plane023.geometry}
              material={materials["Gold.002"]}
              position={[-1.52, 0.04, 0.03]}
              rotation={[-Math.PI, 0, 0]}
              scale={[-0.02, -0.02, -0.01]}
            />
            <mesh
              name="Plane024"
              geometry={nodes.Plane024.geometry}
              material={materials["Gold.002"]}
              position={[-1.53, 0.13, 0.03]}
              rotation={[-Math.PI, 0, 0]}
              scale={[-0.02, -0.02, -0.01]}
            />
            <mesh
              name="Plane025"
              geometry={nodes.Plane025.geometry}
              material={materials["Gold.002"]}
              position={[1.52, 0.13, -0.01]}
              rotation={[Math.PI / 2, -0.01, -0.17]}
              scale={[0.03, 0.02, 0.03]}
            />
            <mesh
              name="Plane026"
              geometry={nodes.Plane026.geometry}
              material={materials["Gold.002"]}
              position={[1.67, -0.05, -0.04]}
              rotation={[Math.PI / 2, 0, -0.16]}
              scale={[0.02, 0.01, 0.01]}
            />
            <mesh
              name="Plane027"
              geometry={nodes.Plane027.geometry}
              material={materials["Gold.002"]}
              position={[-0.37, 0.4, -0.06]}
              rotation={[0, 0, -1.7]}
              scale={0.03}
            />
            <mesh
              name="Plane028"
              geometry={nodes.Plane028.geometry}
              material={materials["Gold.002"]}
              position={[-2.16, 0, -0.06]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.03}
            />
            <mesh
              name="Plane029"
              geometry={nodes.Plane029.geometry}
              material={materials["Gold.002"]}
              position={[-0.58, 0.04, -0.12]}
              rotation={[0, -0.01, 0]}
            />
            <mesh
              name="Screw_1"
              geometry={nodes.Screw_1.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1001"
              geometry={nodes.Screw_1001.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1002"
              geometry={nodes.Screw_1002.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1003"
              geometry={nodes.Screw_1003.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1004"
              geometry={nodes.Screw_1004.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1005"
              geometry={nodes.Screw_1005.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1006"
              geometry={nodes.Screw_1006.geometry}
              material={materials["Gold.002"]}
            />
            <mesh
              name="Screw_1007"
              geometry={nodes.Screw_1007.geometry}
              material={materials["Gold.002"]}
              position={[-1.27, -0.37, 0.01]}
              rotation={[0, 0, 1.77]}
              scale={0.8}
            />
            <mesh
              name="Screw_1008"
              geometry={nodes.Screw_1008.geometry}
              material={materials["Gold.002"]}
              position={[-1.45, -0.37, 0.01]}
              rotation={[0, 0, -0.6]}
              scale={0.8}
            />
            <mesh
              name="Screw_1009"
              geometry={nodes.Screw_1009.geometry}
              material={materials["Gold.002"]}
              position={[-1.27, 0.01, 0]}
              rotation={[0, 0, 0.88]}
            />
            <mesh
              name="Screw_1010"
              geometry={nodes.Screw_1010.geometry}
              material={materials["Gold.002"]}
              position={[-1.43, -0.04, 0]}
              rotation={[0, 0, -0.78]}
            />
            <mesh
              name="Screw_1011"
              geometry={nodes.Screw_1011.geometry}
              material={materials["Gold.002"]}
              position={[-1.37, 0.15, 0]}
              rotation={[0, 0, -0.84]}
            />
            <mesh
              name="Screw_1012"
              geometry={nodes.Screw_1012.geometry}
              material={materials["Gold.002"]}
              position={[-0.32, 0.12, 0]}
            />
            <mesh
              name="Screw_1013"
              geometry={nodes.Screw_1013.geometry}
              material={materials["Gold.002"]}
              position={[-1.56, -0.01, 0.01]}
              rotation={[0, 0, -0.96]}
            />
            <mesh
              name="Screw_1014"
              geometry={nodes.Screw_1014.geometry}
              material={materials["Gold.002"]}
              position={[-1.56, 0.08, 0.01]}
              rotation={[0, 0, -1.82]}
            />
            <mesh
              name="Screw_1015"
              geometry={nodes.Screw_1015.geometry}
              material={materials["Gold.002"]}
              position={[-1.56, 0.18, 0.01]}
              rotation={[0, 0, -2.38]}
            />
            <mesh
              name="Screw_1016"
              geometry={nodes.Screw_1016.geometry}
              material={materials["Gold.002"]}
              position={[-0.82, -0.13, 0]}
              rotation={[0, 0, 1.01]}
              scale={0.61}
            />
            <mesh
              name="Screw_1017"
              geometry={nodes.Screw_1017.geometry}
              material={materials["Gold.002"]}
              position={[-0.82, 0.19, 0]}
              rotation={[0, 0, 0.61]}
              scale={0.61}
            />
            <mesh
              name="Screw_1018"
              geometry={nodes.Screw_1018.geometry}
              material={materials["Gold.002"]}
              position={[1.67, -0.05, -0.04]}
              rotation={[-1.83, 1, -2.83]}
              scale={0.05}
            />
            <mesh
              name="Screw_1019"
              geometry={nodes.Screw_1019.geometry}
              material={materials["Gold.002"]}
              position={[-0.47, 0.12, -0.13]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1.37}
            />
            <mesh
              name="Screw_1020"
              geometry={nodes.Screw_1020.geometry}
              material={materials["Gold.002"]}
              position={[-0.69, 0.12, -0.13]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1.37}
            />
            <mesh
              name="Screw_1021"
              geometry={nodes.Screw_1021.geometry}
              material={materials["Gold.002"]}
              position={[-0.47, -0.05, -0.13]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1.37}
            />
            <mesh
              name="Screw_1022"
              geometry={nodes.Screw_1022.geometry}
              material={materials["Gold.002"]}
              position={[-0.69, -0.05, -0.13]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={1.37}
            />
            <mesh
              name="Screw_1024"
              geometry={nodes.Screw_1024.geometry}
              material={materials["Gold.002"]}
              position={[1.81, 0.07, -0.11]}
              rotation={[1.83, 1, 2.83]}
              scale={0.05}
            />
            <mesh
              name="Spiral001"
              geometry={nodes.Spiral001.geometry}
              material={materials["Gold.002"]}
              position={[-1.61, -0.06, 0.02]}
              rotation={[0, -0.11, -Math.PI / 2]}
              scale={0}
            />
            <mesh
              name="Spiral002"
              geometry={nodes.Spiral002.geometry}
              material={materials["Gold.002"]}
              position={[-1.61, 0.04, 0.02]}
              rotation={[0, -0.11, -Math.PI / 2]}
              scale={0}
            />
            <mesh
              name="Spiral003"
              geometry={nodes.Spiral003.geometry}
              material={materials["Gold.002"]}
              position={[-1.61, 0.13, 0.02]}
              rotation={[0, -0.11, -Math.PI / 2]}
              scale={0}
            />
          </mesh>
        </group>
        <group name="NurbsCurve001" position={[23.24, 6.6, 0.98]} />
        <group name="NurbsCurve002" position={[23.44, 6.6, 0.97]} />
        <group name="NurbsCurve003" position={[14.46, 6.6, -11.95]} />
        <group name="NurbsCurve004" position={[-1.55, 6.6, -12.26]} />
        <group name="NurbsCurve005" position={[8.33, 6.61, 13.91]} />
        <group name="NurbsCurve" position={[41.19, 4.33, 0.98]} />
        <PerspectiveCamera
          name="Camera"
          makeDefault={cam1}
          far={1000}
          near={0}
          fov={90.71}
          position={[42.19, 4.33, -0.02]}
          rotation={[-Math.PI, camZ, -1.59]}
        />
        <PerspectiveCamera
          name="Camera001"
          makeDefault={cam2}
          far={1000}
          near={0.1}
          fov={90.71}
          position={[23.46, 6.6, -0.02]}
          rotation={[-Math.PI, camZ, -Math.PI]}
        />
        <PerspectiveCamera
          name="Camera002"
          makeDefault={cam3}
          far={1000}
          near={0.1}
          fov={90.71}
          position={[23.44, 6.6, -0.03]}
          rotation={[0, -camZ, 0]}
        />
        <PerspectiveCamera
          name="Camera003"
          makeDefault={cam4}
          far={1000}
          near={0.1}
          fov={90.71}
          position={[9.35, 6.61, 12.4]}
          rotation={[-Math.PI, camZ, -Math.PI]}
        />
        <PerspectiveCamera
          name="Camera004"
          makeDefault={cam5}
          far={1000}
          near={0.1}
          fov={90.71}
          position={[15.48, 6.6, -12.45]}
          rotation={[0, -camZ, 0]}
        />
        <PerspectiveCamera
          name="Camera005"
          makeDefault={cam6}
          far={1000}
          near={0.1}
          fov={90.71}
          position={[-0.52, 6.6, -12.76]}
          rotation={[0, -camZ, 0]}
        />
        <mesh
          name="Skull002"
          geometry={nodes.Skull002.geometry}
          material={materials["Material.015"]}
          position={[19.53, 6.36, -19.41]}
          rotation={[-0.45, 0, 0]}
          scale={5.79}
        />
        {/* <mesh name="Pillow_5_Cube000" geometry={nodes.Pillow_5_6ube000.geometry} material={materials['Material.007']} position={[19.41, 5.46, -19.48]} rotation={[0.36, -0.09, 0.38]} scale={10.87} /> */}
        <mesh
          name="Katana_blade"
          geometry={nodes.Katana_blade.geometry}
          material={materials["Material.013"]}
          position={[14.12, 5.34, -18.39]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={5.4}
        />
        {/* <mesh name="Katana_scabbard" geometry={nodes.Katana_sca6bard.geometry} material={materials['Material.014']} position={[13.93, 5.23, -17.99]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={5.4} /> */}
        {/* <mesh name="Hammer_Sledge" geometry={nodes.Hammer_Sledg6.geometry} material={materials['guitar_base.009']} position={[-0.14, 5.23, -19.24]} rotation={[0.11, -0.73, 0]} scale={0.04} /> */}
        <mesh
          name="Hammer_Sledge2"
          geometry={nodes.Hammer_Sledge2.geometry}
          material={materials["Material.013"]}
          position={[-1.82, 5.15, -19.01]}
          rotation={[1.23, 0, 0]}
          scale={0.04}
        />
        <mesh
          name="Mask"
          geometry={nodes.Mask.geometry}
          material={materials["guitar_base.006"]}
          position={[-32.18, 10.6, 16.72]}
          rotation={[0, 1.57, 0]}
          scale={14.1}
        />
        <mesh
          name="claymore_dagger"
          geometry={nodes.claymore_dagger.geometry}
          material={materials["Metal.003"]}
          position={[-4.62, 5.2, -18.37]}
          rotation={[-Math.PI, 0.76, -Math.PI]}
          scale={7.2}
        />
        <mesh
          name="claymore_dagger_sheath"
          geometry={nodes.claymore_dagger_sheath.geometry}
          material={materials["Material.009"]}
          position={[-5.48, 5.18, -18.01]}
          rotation={[-Math.PI, 0.75, -Math.PI]}
          scale={8.07}
        />
        <mesh
          name="damascus_claymore"
          geometry={nodes.damascus_claymore.geometry}
          material={materials["Metal.002"]}
          position={[3.06, 5.22, -18.32]}
          rotation={[0, 1.57, 0]}
          scale={5.39}
        />
        <mesh
          name="damascus_claymore_sheath"
          geometry={nodes.damascus_claymore_sheath.geometry}
          material={materials["Material.009"]}
          position={[0, 5.27, -17.7]}
          rotation={[0, 1.57, 0.02]}
          scale={5.39}
        />
        <mesh
          name="Axe"
          geometry={nodes.Axe.geometry}
          material={materials["Material.036"]}
          position={[3.9, 5.31, -21.37]}
          rotation={[-Math.PI / 2, 0, 2.33]}
          scale={1.57}
        />
        <mesh
          name="Ceramic_frog_high-poly"
          geometry={nodes["Ceramic_frog_high-poly"].geometry}
          material={materials["guitar_base.005"]}
          position={[-31.14, 7.55, -8.44]}
          rotation={[0, 1.22, 0]}
          scale={6.74}
        />
        <mesh
          name="Rock_18_low"
          geometry={nodes.Rock_18_low.geometry}
          material={materials["Material.036"]}
          position={[-3.77, 5.32, -19.66]}
          rotation={[1.55, -0.56, 1.49]}
          scale={0.7}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={materials["Material.001"]}
          position={[35.51, -1.32, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-7.9, -0.05, -22.59]}
        />
        <mesh
          name="Cube009"
          geometry={nodes.Cube009.geometry}
          material={materials["Material.007"]}
          position={[4.09, 7.19, 22.43]}
          scale={[38.71, 8.62, 0.13]}
        />
        <mesh
          name="Cube011"
          geometry={nodes.Cube011.geometry}
          material={materials["Material.007"]}
          position={[4.09, 7.19, -22.37]}
          scale={[38.71, 8.62, 0.13]}
        />
        <mesh
          name="Cube012"
          geometry={nodes.Cube012.geometry}
          material={materials["Material.007"]}
          position={[-32.96, 5.85, -0.31]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.33, -10.06, -23.02]}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={materials["Material.007"]}
          position={[17.95, 5.41, 0]}
          scale={[0.18, 3.14, 2.15]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.002"]}
          position={[-12.32, 0.9, 0]}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials["Material.003"]}
          position={[15.46, 0.92, 16.8]}
        />
        <mesh
          name="Plane002"
          geometry={nodes.Plane002.geometry}
          material={materials.Material}
          position={[15.19, 0.78, 16.98]}
          scale={[0.97, 20.74, 0.97]}
        />
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials["Material.003"]}
          position={[-18.79, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane004"
          geometry={nodes.Plane004.geometry}
          material={materials["Material.002"]}
          position={[-18.79, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane005"
          geometry={nodes.Plane005.geometry}
          material={materials["Material.007"]}
          position={[-27.52, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane006"
          geometry={nodes.Plane006.geometry}
          material={materials["Material.003"]}
          position={[-27.52, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane007"
          geometry={nodes.Plane007.geometry}
          material={materials["Material.005"]}
          position={[-10.36, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane008"
          geometry={nodes.Plane008.geometry}
          material={materials["Material.003"]}
          position={[-10.36, 8.84, 22.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.82, 1, 4.4]}
        />
        <mesh
          name="Plane009"
          geometry={nodes.Plane009.geometry}
          material={materials["Material.002"]}
          position={[-23.34, 3.59, -9.14]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[4.1, 1.89, 1.6]}
        />
        <mesh
          name="Plane010"
          geometry={nodes.Plane010.geometry}
          material={materials["Material.003"]}
          position={[-23.34, 3.59, -9.14]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[4.1, 1.89, 1.6]}
        />
        <mesh
          name="Plane011"
          geometry={nodes.Plane011.geometry}
          material={materials["Material.003"]}
          position={[-32.46, 7.03, -4.93]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[6.02, 1, 16.92]}
        />
        <mesh
          name="Cube014"
          geometry={nodes.Cube014.geometry}
          material={materials["Material.007"]}
          position={[42.74, 5.85, -0.31]}
          rotation={[-Math.PI, 0, 0]}
          scale={[-0.33, -10.06, -23.02]}
        />
        <mesh
          name="Plane012"
          geometry={nodes.Plane012.geometry}
          material={materials["Material.009"]}
          position={[12.97, 3.84, -17.69]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.42, 7.51, 0.75]}
        />
        <mesh
          name="Plane013"
          geometry={nodes.Plane013.geometry}
          material={materials["Material.010"]}
          position={[12.85, 3.37, -17.55]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.44, 2.81, 0.78]}
        />
        <mesh
          name="Plane014"
          geometry={nodes.Plane014.geometry}
          material={materials["Material.011"]}
          position={[-4.31, 3.37, -17.55]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.44, 2.81, 0.78]}
        />
        <mesh
          name="Plane015"
          geometry={nodes.Plane015.geometry}
          material={materials["Material.012"]}
          position={[-4.19, 3.84, -17.69]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.42, 7.51, 0.75]}
        />
        <mesh
          name="Cube018"
          geometry={nodes.Cube018.geometry}
          material={materials["hammer_mat2.001"]}
          position={[19.43, 5.22, -17.9]}
          rotation={[2.03, 0, 0]}
          scale={[0.26, 0.01, 0.04]}
        />
        <mesh
          name="Decorative_05167"
          geometry={nodes.Decorative_05167.geometry}
          material={materials.wire_027177027}
          position={[19.43, 5.22, -17.9]}
          rotation={[-2.68, 0, 0]}
          scale={0}
        />
        <mesh
          name="Decorative_05167001"
          geometry={nodes.Decorative_05167001.geometry}
          material={materials.wire_027177027}
          position={[19.61, 5.25, -17.9]}
          rotation={[-2.87, 0.38, 0.92]}
          scale={0}
        />
        <mesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials["Gold.001"]}
          position={[19.61, 5.25, -17.9]}
          rotation={[2.3, -0.84, 0.59]}
          scale={[0.26, 0.01, 0.04]}
        />
        <mesh
          name="MI_LOD0"
          geometry={nodes.MI_LOD0.geometry}
          material={materials["guitar_base.009"]}
          position={[12.97, 1.01, 1.04]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0_001"
          geometry={nodes.MI_LOD0_001.geometry}
          material={materials["Material.020"]}
          position={[12.97, 1.01, 1.04]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0_002"
          geometry={nodes.MI_LOD0_002.geometry}
          material={materials["Material.008"]}
          position={[12.97, 1.01, 1.04]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0001"
          geometry={nodes.MI_LOD0001.geometry}
          material={materials["guitar_base.017"]}
          position={[0.21, 1.01, 2.52]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0_001001"
          geometry={nodes.MI_LOD0_001001.geometry}
          material={materials["Material.020"]}
          position={[0.21, 1.01, 2.52]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0_002001"
          geometry={nodes.MI_LOD0_002001.geometry}
          material={materials["Material.004"]}
          position={[0.21, 1.01, 2.52]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD1001"
          geometry={nodes.MI_LOD1001.geometry}
          material={materials["guitar_base.006"]}
          position={[8.09, 1.01, 0.05]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD1_001001"
          geometry={nodes.MI_LOD1_001001.geometry}
          material={materials["Material.020"]}
          position={[8.09, 1.01, 0.05]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD1_002001"
          geometry={nodes.MI_LOD1_002001.geometry}
          material={materials["Material.008"]}
          position={[8.09, 1.01, 0.05]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD0004"
          geometry={nodes.MI_LOD0004.geometry}
          material={materials["guitar_base.007"]}
          position={[-6.7, 1.01, 1.27]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2_002003"
          geometry={nodes.MI_LOD2_002003.geometry}
          material={materials["Material.004"]}
          position={[-2.02, 1.01, -1.24]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2_001003"
          geometry={nodes.MI_LOD2_001003.geometry}
          material={materials["Material.020"]}
          position={[-2.02, 1.01, -1.24]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2003"
          geometry={nodes.MI_LOD2003.geometry}
          material={materials["guitar_base.009"]}
          position={[-2.02, 1.01, -1.24]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2_002004"
          geometry={nodes.MI_LOD2_002004.geometry}
          material={materials["Material.004"]}
          position={[3.34, 1.01, -0.35]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2_001004"
          geometry={nodes.MI_LOD2_001004.geometry}
          material={materials["Material.020"]}
          position={[3.34, 1.01, -0.35]}
          scale={0.02}
        />
        <mesh
          name="MI_LOD2004"
          geometry={nodes.MI_LOD2004.geometry}
          material={materials["guitar_base.004"]}
          position={[3.34, 1.01, -0.35]}
          scale={0.02}
        />
        <mesh
          name="Matteuccia_struthiopteris__A001"
          geometry={nodes.Matteuccia_struthiopteris__A001.geometry}
          material={materials.leaf}
          position={[34.71, -1.25, -16.87]}
          scale={0.44}
        />
        <mesh
          name="Matteuccia_struthiopteris__B001"
          geometry={nodes.Matteuccia_struthiopteris__B001.geometry}
          material={materials.leaf}
          position={[34.71, -1.25, -16.87]}
          scale={0.44}
        />
        <mesh
          name="Matteuccia_struthiopteris__C001"
          geometry={nodes.Matteuccia_struthiopteris__C001.geometry}
          material={materials.leaf}
          position={[34.71, -1.25, -16.87]}
          scale={0.44}
        />
        <mesh
          name="Matteuccia_struthiopteris__A001001"
          geometry={nodes.Matteuccia_struthiopteris__A001001.geometry}
          material={materials["leaf.001"]}
          position={[34.71, -1.25, 17.38]}
          scale={0.44}
        />
        <mesh
          name="Matteuccia_struthiopteris__B001001"
          geometry={nodes.Matteuccia_struthiopteris__B001001.geometry}
          material={materials["leaf.001"]}
          position={[34.71, -1.25, 17.38]}
          scale={0.44}
        />
        <mesh
          name="Matteuccia_struthiopteris__C001001"
          geometry={nodes.Matteuccia_struthiopteris__C001001.geometry}
          material={materials["leaf.001"]}
          position={[34.71, -1.25, 17.38]}
          scale={0.44}
        />
        <group onClick={LanzarTambores}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        >
          <mesh
            name="Куб"
            geometry={nodes.Куб.geometry}
            material={materials["Mask mat.001"]}
            position={[6.56, 4.79, 19.19]}
            rotation={[0, 0.34, 0]}
            scale={5.6}
          />
          <mesh
            name="Куб001"
            geometry={nodes.Куб001.geometry}
            material={materials["guitar_base.008"]}
            position={[8.53, 3.88, 19.56]}
            rotation={[0, -0.19, 0]}
            scale={5.18}
          />
          <mesh
            name="Куб002"
            geometry={nodes.Куб002.geometry}
            material={materials["guitar_base.008"]}
            position={[8.89, 3.88, 19.25]}
            rotation={[0, -0.19, 0]}
            scale={5.18}
          />
          <mesh
            name="Цилиндр"
            geometry={nodes.Цилиндр.geometry}
            material={materials["guitar_base.001"]}
            position={[8.28, 3.8, 19.74]}
            rotation={[0, -0.84, 0]}
            scale={5.18}
          />
          <mesh
            name="Цилиндр001"
            geometry={nodes.Цилиндр001.geometry}
            material={materials["guitar_base.002"]}
            position={[6.56, 3.2, 19.2]}
            rotation={[0, -0.19, 0]}
            scale={5.18}
          />
          <mesh
            name="Цилиндр002"
            geometry={nodes.Цилиндр002.geometry}
            material={materials["guitar_base.005"]}
            position={[4.28, 2.01, 18.78]}
            rotation={[0, -0.19, 0]}
            scale={4.91}
          />
          <mesh
            name="Цилиндр004"
            geometry={nodes.Цилиндр004.geometry}
            material={materials.guitar_base}
            position={[8.57, 3.6, 19.58]}
            rotation={[0, -0.19, 0]}
            scale={4.8}
          />
          <mesh
            name="Цилиндр006"
            geometry={nodes.Цилиндр006.geometry}
            material={materials["guitar_base.004"]}
            position={[7.01, 4.79, 19.98]}
            rotation={[-0.29, -0.23, 0.05]}
            scale={0.1}
          />
          <mesh
            name="Цилиндр017"
            geometry={nodes.Цилиндр017.geometry}
            material={materials["Material.013"]}
            position={[4.33, 3.39, 18.94]}
            rotation={[0, 1.55, 0]}
            scale={5.18}
          />
          <mesh
            name="Retopo_Цилиндр005"
            geometry={nodes.Retopo_Цилиндр005.geometry}
            material={materials["guitar_base.009"]}
            position={[7.23, 3.27, 18.12]}
            rotation={[1.82, -1.24, -Math.PI]}
            scale={4.76}
          />
        </group>
        <group onClick={LanzarTambores}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        >
          <mesh
            name="violin_body"
            geometry={nodes.violin_body.geometry}
            material={materials["guitar_base.015"]}
            position={[6.65, 8.85, 22.02]}
            rotation={[Math.PI, -0.01, Math.PI]}
            scale={0.02}
          />
          <mesh
            name="violinbowSAMEmaterial"
            geometry={nodes.violinbowSAMEmaterial.geometry}
            material={materials["guitar_base.002"]}
            position={[6.55, 10.96, 22.07]}
            rotation={[Math.PI, -0.01, Math.PI]}
            scale={0.02}
          />
          <mesh
            name="violinrestbody"
            geometry={nodes.violinrestbody.geometry}
            material={materials["guitar_base.002"]}
            position={[6.64, 9.89, 21.78]}
            rotation={[Math.PI, -0.01, Math.PI]}
            scale={0.02}
          />
          <mesh
            name="violintinypiecesSAMEmaterial"
            geometry={nodes.violintinypiecesSAMEmaterial.geometry}
            material={materials["guitar_base.002"]}
            position={[6.55, 10.96, 22.07]}
            rotation={[Math.PI, -0.01, Math.PI]}
            scale={0.02}
          />
        </group>
        <mesh
          name="Body"
          geometry={nodes.Body.geometry}
          material={materials["Material.015"]}
          position={[-31.21, 7.87, -13.63]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={9.21}
        />
        <mesh
          name="BtnA"
          geometry={nodes.BtnA.geometry}
          material={materials["Material.023"]}
          position={[-31.1, 7.83, -14.04]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={[8.8, 8.8, 9.21]}
        />
        <mesh
          name="BtnB"
          geometry={nodes.BtnB.geometry}
          material={materials["Material.023"]}
          position={[-31.1, 7.83, -13.89]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={[8.8, 8.8, 9.21]}
        />
        <mesh
          name="BtnSelect"
          geometry={nodes.BtnSelect.geometry}
          material={materials["Material.009"]}
          position={[-31.09, 7.82, -13.53]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={9.21}
        />
        <mesh
          name="BtnStart"
          geometry={nodes.BtnStart.geometry}
          material={materials["Material.009"]}
          position={[-31.09, 7.82, -13.67]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={9.21}
        />
        <mesh
          name="DPad"
          geometry={nodes.DPad.geometry}
          material={materials["Material.016"]}
          position={[-31.12, 7.86, -13.26]}
          rotation={[-1.56, 0.99, 1.58]}
          scale={9.21}
        />
        <mesh
          name="Cube024"
          geometry={nodes.Cube024.geometry}
          material={materials["Material.018"]}
          position={[15.98, 5.07, -20.3]}
          scale={[-0.93, -0.13, -0.93]}
        />
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={materials["Bronze_Procedural_001.001"]}
          position={[15.6, 5.88, -20.08]}
          rotation={[0, -1.57, 0]}
          scale={0.21}
        />
        <mesh
          name="Cylinder011"
          geometry={nodes.Cylinder011.geometry}
          material={materials["Bronze_Procedural_001.001"]}
          position={[15.6, 5.88, -20.08]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.73, 0.78, 0.73]}
        />
        <mesh
          name="Cylinder012"
          geometry={nodes.Cylinder012.geometry}
          material={materials["Bronze_Procedural_001.001"]}
          position={[16.35, 6.5, -20.08]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.15}
        />
        <mesh
          name="Cylinder013"
          geometry={nodes.Cylinder013.geometry}
          material={materials["Material.019"]}
          position={[16.35, 6.5, -20.08]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.15}
        />
        <mesh
          name="Plane031"
          geometry={nodes.Plane031.geometry}
          material={materials["Material.013"]}
          position={[16.01, 6.55, -20.33]}
          scale={0.73}
        />
        <mesh
          name="Plane032"
          geometry={nodes.Plane032.geometry}
          material={materials["Material.013"]}
          position={[16.01, 6.55, -20.33]}
          scale={0.73}
        />
        <group onClick={LanzarArmor}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        >

          <group
            name="Soi_SimpleArmor"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane381"
              geometry={nodes.Plane381.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane381_1"
              geometry={nodes.Plane381_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <mesh
            name="Soi_SimpleArmor_Boots"
            geometry={nodes.Soi_SimpleArmor_Boots.geometry}
            material={materials["Metal.003"]}
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          />
          <group
            name="Soi_SimpleArmor_Frontuards"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane415"
              geometry={nodes.Plane415.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane415_1"
              geometry={nodes.Plane415_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            name="Soi_SimpleArmor_Gloves"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane389"
              geometry={nodes.Plane389.geometry}
              material={materials["Metal.007"]}
            />
            <mesh
              name="Plane389_1"
              geometry={nodes.Plane389_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <mesh
            name="Soi_SimpleArmor_Helmet"
            geometry={nodes.Soi_SimpleArmor_Helmet.geometry}
            material={materials["Material.024"]}
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          />
          <group
            name="Soi_SimpleArmor_Hood"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane392"
              geometry={nodes.Plane392.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane392_1"
              geometry={nodes.Plane392_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            name="Soi_SimpleArmor_Kneeguards"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane396"
              geometry={nodes.Plane396.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane396_1"
              geometry={nodes.Plane396_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            name="Soi_SimpleArmor_Sideguards"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane394"
              geometry={nodes.Plane394.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane394_1"
              geometry={nodes.Plane394_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            name="Soi_SimpleArmor_Spaulders"
            position={[14.59, 1.75, 19.88]}
            rotation={[0, 0, -Math.PI]}
            scale={-5.99}
          >
            <mesh
              name="Plane390"
              geometry={nodes.Plane390.geometry}
              material={materials["Metal.003"]}
            />
            <mesh
              name="Plane390_1"
              geometry={nodes.Plane390_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
        </group>
        <group onClick={LanzarGuitar1}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
          name="guitar_base"
          position={[-1.28, 3.92, 21.82]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={-2.34}
        >
          <mesh
            name="Plane061"
            geometry={nodes.Plane061.geometry}
            material={materials["guitar_base.014"]}
          />
          <mesh
            name="Plane061_1"
            geometry={nodes.Plane061_1.geometry}
            material={materials["guitar_base.015"]}
          />
          <mesh
            name="Plane061_2"
            geometry={nodes.Plane061_2.geometry}
            material={materials["guitar_base.016"]}
          />
          <mesh
            name="Plane061_3"
            geometry={nodes.Plane061_3.geometry}
            material={materials["guitar_base.017"]}
          />
          <mesh
            name="Plane061_4"
            geometry={nodes.Plane061_4.geometry}
            material={materials["guitar_base_in.002"]}
          />
          <mesh
            name="guitar_adjust_strings"
            geometry={nodes.guitar_adjust_strings.geometry}
            material={materials["Material.051"]}
            position={[-0.02, 0.51, 0.10]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-0.015}
          />
          <mesh
            name="guitar_cable_fixing_base"
            geometry={nodes.guitar_cable_fixing_base.geometry}
            material={materials["Material.052"]}
            position={[-0.02, 0.51, -0.01]}
            scale={-0.1}
          />
          <mesh
            name="guitar_freeze_strings"
            geometry={nodes.guitar_freeze_strings.geometry}
            material={materials["Material.051"]}
            position={[-0.02, 1.1, 0.5]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[-0.02, -0.01, -0.02]}
          />
          <mesh
            name="guitar_freeze_strings001"
            geometry={nodes.guitar_freeze_strings001.geometry}
            material={materials["basketball_black.002"]}
            position={[-0.02, 0.65, -0.1]}
            scale={-0.01}
          />
          <group
            name="guitar_handle"
            position={[-0.02, 0.455, -0.01]}
            scale={[-0.09, -0.02, -0.07]}
          >
            <mesh
              name="Plane064"
              geometry={nodes.Plane064.geometry}
              material={materials["guitar_base.002"]}
            />
            <mesh
              name="Plane064_1"
              geometry={nodes.Plane064_1.geometry}
              material={materials["Material.053"]}
            />
          </group>
          <mesh
            name="guitar_handle001"
            geometry={nodes.guitar_handle001.geometry}
            material={materials["Material.054"]}
            position={[-0.02, 0.45, -0.01]}
            scale={[-0.09, -0.02, -0.07]}
          />
          <mesh
            name="guitar_strings"
            geometry={nodes.guitar_strings.geometry}
            material={materials["Material.055"]}
            position={[-0.02, 0.52, -0.01]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={-0.67}
          />
        </group>
        <group onClick={LanzarYunke}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        >
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials["Material.038"]}
            position={[-1.37, 5.22, -19.96]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.05, 0.04, 0.04]}
          />
          <mesh
            name="nose"
            geometry={nodes.nose.geometry}
            material={materials["Material.038"]}
            position={[-1.37, 5.22, -19.96]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.05, 0.04, 0.04]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/museu1.glb");
