/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 museuCams.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function MuseuCams ({ props, playState, camZ, cam1, cam2, cam3, cam4 }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/museuCams.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions);
    if(cam1){
      if (playState) {
        actions['CameraAction.001'].play()
        actions['CameraAction.001'].timeScale = 0.3;
      } else {
        actions['CameraAction.001'].timeScale = 0;
      }
    } else if(cam2){
      if (playState) {
        actions['Camera.001Action'].play()
        actions['Camera.001Action'].timeScale = 0.3;
      } else {
        actions['Camera.001Action'].timeScale = 0;
      }
    } else if(cam3){
      if (playState) {
        actions['Camera.002Action.001'].play()
        actions['Camera.002Action.001'].timeScale = 0.3;
      } else {
        actions['Camera.002Action.001'].timeScale = 0;
      }
    } else if(cam4){
      if (playState) {
        actions['Camera.003Action.001'].play()
        actions['Camera.003Action.001'].timeScale = 0.3;
      } else {
        actions['Camera.003Action.001'].timeScale = 0;
      }
    }
  }, [playState, cam1, cam2, cam3, cam4])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsCurve" position={[44.53, 3.69, 0.91]} />
        <group name="NurbsCurve001" position={[22.19, 5.93, 0.42]} />
        <group name="NurbsCurve002" position={[23.02, 5.93, -0.58]} rotation={[-Math.PI, 0, 0]} scale={[0.45, 1, 1]} />
        <group name="NurbsCurve003" position={[14.68, 5.93, -11.8]} />
        <group name="MESH_BS09_NeriumOleander_A_LOD0" position={[49.1, 0, 0]} scale={0.01} />
        <group name="MESH_BS09_NeriumOleander_Y_LOD1" position={[9.56, 1.01, 4.07]} scale={0.02}>
          <mesh name="MI_LOD1002" geometry={nodes.MI_LOD1002.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD1_001002" geometry={nodes.MI_LOD1_001002.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD1_002002" geometry={nodes.MI_LOD1_002002.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_A_LOD1" position={[5.03, 1.01, 3.46]} scale={0.01}>
          <mesh name="MI_LOD1" geometry={nodes.MI_LOD1.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD1_001" geometry={nodes.MI_LOD1_001.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD1_002" geometry={nodes.MI_LOD1_002.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_A_LOD2" position={[-6.05, 1.01, -3.73]} scale={0.02}>
          <mesh name="MI_LOD2" geometry={nodes.MI_LOD2.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD2_001" geometry={nodes.MI_LOD2_001.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD2_002" geometry={nodes.MI_LOD2_002.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_M_LOD0" position={[0.21, 1.01, 2.52]} scale={0.02} />
        <group name="MESH_BS09_NeriumOleander_M_LOD1" position={[8.09, 1.01, 0.05]} scale={0.02} />
        <group name="MESH_BS09_NeriumOleander_M_LOD2" position={[1.75, 1.01, -3.73]} scale={0.02}>
          <mesh name="MI_LOD2001" geometry={nodes.MI_LOD2001.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD2_001001" geometry={nodes.MI_LOD2_001001.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD2_002001" geometry={nodes.MI_LOD2_002001.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_Y_LOD0" position={[-1.52, 1.01, -4.77]} scale={0.02}>
          <mesh name="MI_LOD0002" geometry={nodes.MI_LOD0002.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD0_001002" geometry={nodes.MI_LOD0_001002.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD0_002002" geometry={nodes.MI_LOD0_002002.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_Y_LOD2" position={[9.56, 1.01, -3.73]} scale={0.02}>
          <mesh name="MI_LOD2002" geometry={nodes.MI_LOD2002.geometry} material={materials.BS09_Bark01_su} />
          <mesh name="MI_LOD2_001002" geometry={nodes.MI_LOD2_001002.geometry} material={materials.BS09_Leaf01_su} />
          <mesh name="MI_LOD2_002002" geometry={nodes.MI_LOD2_002002.geometry} material={materials.BS09_Flower01_su} />
        </group>
        <group name="MESH_BS09_NeriumOleander_M_LOD0001" position={[13.48, 1.01, -3.53]} scale={0.02}>
          <mesh name="MI_LOD0003" geometry={nodes.MI_LOD0003.geometry} material={materials['BS09_Bark01_su.001']} />
          <mesh name="MI_LOD0_001003" geometry={nodes.MI_LOD0_001003.geometry} material={materials['BS09_Leaf01_su.001']} />
          <mesh name="MI_LOD0_002003" geometry={nodes.MI_LOD0_002003.geometry} material={materials['BS09_Flower01_su.001']} />
        </group>
        <group name="MESH_BS09_NeriumOleander_A_LOD0001" position={[24.93, 0, 0]} scale={0.01} />
        <group name="MESH_BS09_NeriumOleander_A_LOD2001" position={[-2.02, 1.01, -1.24]} scale={0.02} />
        <group name="MESH_BS09_NeriumOleander_Y_LOD2001" position={[3.34, 1.01, -0.35]} scale={0.02} />
        <group name="MESH_BS09_NeriumOleander_Y_LOD0001" position={[-3.24, 1.01, 3.82]} scale={0.02}>
          <mesh name="MI_LOD0005" geometry={nodes.MI_LOD0005.geometry} material={materials['BS09_Bark01_su.005']} />
          <mesh name="MI_LOD0_001005" geometry={nodes.MI_LOD0_001005.geometry} material={materials['BS09_Leaf01_su.005']} />
          <mesh name="MI_LOD0_002005" geometry={nodes.MI_LOD0_002005.geometry} material={materials['BS09_Flower01_su.005']} />
        </group>
        <group name="MESH_BS09_NeriumOleander_M_LOD0002" position={[5.9, 1.01, -3.64]} scale={0.02}>
          <mesh name="MI_LOD0006" geometry={nodes.MI_LOD0006.geometry} material={materials['BS09_Bark01_su.006']} />
          <mesh name="MI_LOD0_001006" geometry={nodes.MI_LOD0_001006.geometry} material={materials['BS09_Leaf01_su.006']} />
          <mesh name="MI_LOD0_002006" geometry={nodes.MI_LOD0_002006.geometry} material={materials['BS09_Flower01_su.006']} />
        </group>
        <PerspectiveCamera name="Camera" makeDefault={cam1} far={100} near={0.1} fov={90.71} position={[42.19, 3.69, -0.09]} rotation={[-Math.PI, camZ, -Math.PI]} />
        <PerspectiveCamera name="Camera001" makeDefault={cam2} far={1000} near={0.1} fov={90.71} position={[23.73, 5.93, -0.09]} rotation={[-Math.PI, camZ, -Math.PI]} />
        <PerspectiveCamera name="Camera002" makeDefault={cam3} far={1000} near={0.1} fov={90.71} position={[23.71, 5.93, -0.08]} rotation={[-Math.PI, camZ, -Math.PI]} />
        <PerspectiveCamera name="Camera003" makeDefault={cam4} far={1000} near={0.1} fov={90.71} position={[15.89, 5.93, -11.48]} rotation={[-Math.PI, camZ, -Math.PI]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-4.13, 0.84, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[-29.17, -0.05, -22.57]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[25.47, 0.66, 0]} scale={[0.44, 0.25, 5.08]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[26.36, 0.19, 0]} scale={[0.44, 0.25, 5.08]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[27.21, -0.22, 0]} scale={[0.44, 0.25, 5.08]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[27.22, -0.18, -13.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.21, -1.09, -8.83]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[27.22, -0.18, 13.9]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.21, -1.09, -8.83]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[35.51, -1.32, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-7.9, -0.05, -22.59]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.001']} position={[28.98, -1.17, 0]} scale={[0.44, 0.25, 5.08]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.004']} position={[4.09, 7.19, 22.43]} scale={[38.71, 8.62, 0.13]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[28.09, -0.69, 0]} scale={[0.44, 0.25, 5.08]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.004']} position={[4.09, 7.19, -22.37]} scale={[38.71, 8.62, 0.13]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.004']} position={[-32.96, 5.85, -0.31]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.33, -10.06, -23.02]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.004']} position={[17.95, 5.41, 0]} scale={[0.18, 3.14, 2.15]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-12.32, 0.9, 0]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[15.46, 0.92, 16.8]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Material} position={[15.19, 0.78, 16.98]} scale={[0.97, 20.74, 0.97]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-18.79, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.006']} position={[-18.79, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.007']} position={[-27.52, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.003']} position={[-27.52, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.005']} position={[-10.36, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.003']} position={[-10.36, 8.84, 22.2]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.82, 1, 4.4]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.002']} position={[-23.34, 3.59, -9.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.1, 1.89, 1.6]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.003']} position={[-23.34, 3.59, -9.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.1, 1.89, 1.6]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.003']} position={[-32.46, 7.03, -4.93]} rotation={[0, 0, -Math.PI / 2]} scale={[6.02, 1, 16.92]} />
        <mesh name="Matteuccia_struthiopteris__C001001" geometry={nodes.Matteuccia_struthiopteris__C001001.geometry} material={materials['leaf.001']} position={[34.71, -1.25, 17.38]} scale={0.44} />
        <mesh name="Matteuccia_struthiopteris__B001001" geometry={nodes.Matteuccia_struthiopteris__B001001.geometry} material={materials['leaf.001']} position={[34.71, -1.25, 17.38]} scale={0.44} />
        <mesh name="Matteuccia_struthiopteris__A001001" geometry={nodes.Matteuccia_struthiopteris__A001001.geometry} material={materials['leaf.001']} position={[34.71, -1.25, 17.38]} scale={0.44} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.009']} position={[12.97, 3.84, -17.69]} rotation={[Math.PI, 0, Math.PI]} scale={[0.42, 7.51, 0.75]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.010']} position={[12.85, 3.37, -17.55]} rotation={[Math.PI, 0, Math.PI]} scale={[0.44, 2.81, 0.78]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.011']} position={[-4.31, 3.37, -17.55]} rotation={[Math.PI, 0, Math.PI]} scale={[0.44, 2.81, 0.78]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.012']} position={[-4.19, 3.84, -17.69]} rotation={[Math.PI, 0, Math.PI]} scale={[0.42, 7.51, 0.75]} />
        <mesh name="Matteuccia_struthiopteris__A001" geometry={nodes.Matteuccia_struthiopteris__A001.geometry} material={materials.leaf} position={[34.71, -1.25, -16.87]} scale={0.44} />
        <mesh name="Matteuccia_struthiopteris__B001" geometry={nodes.Matteuccia_struthiopteris__B001.geometry} material={materials.leaf} position={[34.71, -1.25, -16.87]} scale={0.44} />
        <mesh name="Matteuccia_struthiopteris__C001" geometry={nodes.Matteuccia_struthiopteris__C001.geometry} material={materials.leaf} position={[34.71, -1.25, -16.87]} scale={0.44} />
        <mesh name="MI_LOD0" geometry={nodes.MI_LOD0.geometry} material={materials.BS09_Bark01_su} position={[12.97, 1.01, 1.04]} scale={0.02} />
        <mesh name="MI_LOD0_001" geometry={nodes.MI_LOD0_001.geometry} material={materials.BS09_Leaf01_su} position={[12.97, 1.01, 1.04]} scale={0.02} />
        <mesh name="MI_LOD0_002" geometry={nodes.MI_LOD0_002.geometry} material={materials.BS09_Flower01_su} position={[12.97, 1.01, 1.04]} scale={0.02} />
        <mesh name="MI_LOD0001" geometry={nodes.MI_LOD0001.geometry} material={materials.BS09_Bark01_su} position={[0.21, 1.01, 2.52]} scale={0.02} />
        <mesh name="MI_LOD0_001001" geometry={nodes.MI_LOD0_001001.geometry} material={materials.BS09_Leaf01_su} position={[0.21, 1.01, 2.52]} scale={0.02} />
        <mesh name="MI_LOD0_002001" geometry={nodes.MI_LOD0_002001.geometry} material={materials.BS09_Flower01_su} position={[0.21, 1.01, 2.52]} scale={0.02} />
        <mesh name="MI_LOD1001" geometry={nodes.MI_LOD1001.geometry} material={materials.BS09_Bark01_su} position={[8.09, 1.01, 0.05]} scale={0.02} />
        <mesh name="MI_LOD1_001001" geometry={nodes.MI_LOD1_001001.geometry} material={materials.BS09_Leaf01_su} position={[8.09, 1.01, 0.05]} scale={0.02} />
        <mesh name="MI_LOD1_002001" geometry={nodes.MI_LOD1_002001.geometry} material={materials.BS09_Flower01_su} position={[8.09, 1.01, 0.05]} scale={0.02} />
        <mesh name="MI_LOD0004" geometry={nodes.MI_LOD0004.geometry} material={materials['BS09_Bark01_su.002']} position={[-6.7, 1.01, 1.27]} scale={0.02} />
        <mesh name="MI_LOD2_002003" geometry={nodes.MI_LOD2_002003.geometry} material={materials['BS09_Flower01_su.003']} position={[-2.02, 1.01, -1.24]} scale={0.02} />
        <mesh name="MI_LOD2_001003" geometry={nodes.MI_LOD2_001003.geometry} material={materials['BS09_Leaf01_su.003']} position={[-2.02, 1.01, -1.24]} scale={0.02} />
        <mesh name="MI_LOD2003" geometry={nodes.MI_LOD2003.geometry} material={materials['BS09_Bark01_su.003']} position={[-2.02, 1.01, -1.24]} scale={0.02} />
        <mesh name="MI_LOD2_002004" geometry={nodes.MI_LOD2_002004.geometry} material={materials['BS09_Flower01_su.004']} position={[3.34, 1.01, -0.35]} scale={0.02} />
        <mesh name="MI_LOD2_001004" geometry={nodes.MI_LOD2_001004.geometry} material={materials['BS09_Leaf01_su.004']} position={[3.34, 1.01, -0.35]} scale={0.02} />
        <mesh name="MI_LOD2004" geometry={nodes.MI_LOD2004.geometry} material={materials['BS09_Bark01_su.004']} position={[3.34, 1.01, -0.35]} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/museuCams.glb')
