/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 prueva1.glb
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model({props, playState, camZ}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/prueva1.glb')
  const { actions } = useAnimations(animations, group)
  console.log (actions);

  useEffect(() => {
    if (playState){
      actions['CameraAction.001'].timeScale= 0.3;
      actions['CameraAction.001'].play()
    } else {
      actions['CameraAction.001'].timeScale= 0;
    }
  }, [playState])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsPath" position={[-5.74, 2.51, -6.13]} />
        <PerspectiveCamera name="Camera" makeDefault={true} far={100} near={0.1} fov={70} position={[-7.74, 2.51, -6.13]} rotation={[Math.PI, camZ, Math.PI]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} scale={[26.03, 0.16, 26.03]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[4.2, 5.24, 10.27]} rotation={[0, -0.69, 0]} scale={[0.96, 5.96, 15.03]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[13.53, 4.71, -14.55]} rotation={[0, 0.98, 0]} scale={[1, 5.72, 9.46]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[0, 10.08, 0]} scale={[26.03, 0.16, 26.03]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[24.7, 4.45, 0]} scale={[0.43, 6.8, 26.3]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-25.5, 4.45, 0]} scale={[0.43, 6.8, 26.3]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, 4.14, -24.57]} scale={[26.93, 6.39, 0.47]} />
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[-14.25, 1.87, 11.12]} rotation={[0, -0.65, 0.99]} scale={[6.79, 6.23, 4.42]} />
      </group>
    </group>
  )
}

useGLTF.preload('/prueva1.glb')
